version: '3.8'

services:

  shop-mysql:
    image: mysql
    container_name: shop-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=shop_api
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"

  shop-api:
    image: shop-api:latest
    container_name: shop-api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - shop-mysql

  shop-web:
    build: .
    image: shop-web:latest
    container_name: shop-web
    restart: always
    ports:
      - "80:80"
    depends_on:
      - shop-mysql
      - shop-api
